/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.alphastudioz;

import javax.security.auth.login.LoginException;

public class AlphaBot {

    public static void main(String[] args) throws LoginException {
        Init.build();
    }
}
